### PR TITLE
pubsub with nats example added

### PR DESCRIPTION
**Pull request by BruceWangNo1**

### CODE REVIEW

**Comment by asim** [comment]
I'm not sure it makes sense for us to have this example. It's basically identical to the pubsub example with just the addition of flag flipping for nats. If you want to add more info to the existing pubsub readme to show people how to switch the brokers that might be useful but otherwise I have to close this. 

Also to note your cli/main.go starts a service, this isn't really what we expect of a client. It also manually initialises and connects the broker which again we don't do if using client.Publish, this is done automatically. The same issue exists in the server. If you call service.Run it will initialise and connect the broker.

**Comment by BruceWangNo1** [comment]
@asim Thank you for your appreciation. I just thought I'd be able to help people who are having a hard time to grasp how to build microservices like me.

**Comment by asim** [comment]
We appreciate that but the example you've provided already exists and only required additional info in the readme to indicate the use of --broker=nats or MICRO_BROKER=nats

**Comment by BruceWangNo1** [comment]
Yeah, that's exactly what I was trying to figure out the last two days. This morning I found out that what has been keeping me from making nats as the underlying message queue is that [the example](https://github.com/micro-in-cn/tutorials/blob/d12cdd835099d34fc0a14e5ec903b5b42cffd296/examples/basic-practices/micro-broker/basic/main.go) I was referring left out
```go
cmd.Init()
```
And that is the root cause of broker using https instead of nats.
[Your example](https://github.com/micro/examples/blob/master/broker/main.go) has 
```go
cmd.Init()
```
I can't believe this nonsense cost me two days.

**Pull request closed without merging**
