### PR TITLE
V2 fixes

### PR DESCRIPTION
**Pull request by unicell**

### CODE REVIEW

**Comment by unicell** [comment]
Hi @asim this is the PR containing the fixes while I playing with the code base. There's still other pending fix to in order to let it fully pass the CI.

Let me know if it is a desired approach or you wanna me to break it up into several PRs, one for each example.

**Comment by unicell** [comment]
Till the latest commit above, other than missing `SLACK_WEBHOOK` in project setting, everything else passed CI [1] just fine. Please take a look. @asim 

[1] https://github.com/micro/examples/pull/119/checks?check_run_id=559921766

**Comment by unicell** [comment]
Added a few more commits to entirely cut off dependencies on v1 micro/[cli|go-micro|go-plugins|micro]. Let me know if it is not good. @asim

**Comment by vtolstov** [comment]
big thanks!

**Pull request merged**
