### PR TITLE
GraphQL API example for greeter

### PR DESCRIPTION
**Pull request by andrioid**
A very basic example of using gqlgen with micro/go-web to query the gRPC server.

I tried documenting it as well as possible in the attached README.md with a screenshot of the GraphQL playground that comes with gqlgen.

I'm open to a code-review before merging.

### CODE REVIEW

**Comment by asim** [comment]
Looks good. Thanks very much for contributing! This use of go-web makes me realise we need an api specific library. Go-web will likely morph into something that supports wasm and focus more generally on web development.

**Comment by andrioid** [comment]
I took inspiration in the api/gin example. Is there a better way to introduce http handlers?

**Comment by asim** [comment]
At the moment there's no better way to introduce them. I'll update the examples and let you know as that changes. Looks like there are some build errors.

**Comment by asim** [comment]
`rctx.PushIndex undefined (type *graphql.ResolverContext has no field or method PushIndex)`

Some undefined things

**Comment by andrioid** [comment]
Maybe something with the dependencies I introduced with gqlgen? Builds just fine on my machine (classic excuse)

**Comment by andrioid** [comment]
The error was caused by the generated graphql code wasn't compatible with the latest version of gqlgen. I can't wait for Go1.11!

Maybe the generated files should not be checked-in, but that makes running the example a bit more difficult.

**Comment by asim** [comment]
Gotta keep upto date with dependencies! Hopefully this doesn't break again too soon!

**Comment by andrioid** [comment]
If it does, we'll just add a Makefile to the directory and add running it to the instructions after adding generated.go into .gitignore.

Nice to see it merged. I hope to see more GraphQL in go-land 😄

**Comment by asim** [comment]
Ok make file would be useful. Also which part of this code is generated versus hand coded? We should ensure the two are separated as much as possible so it's clear to the user what they need to write versus what will be generated.

**Comment by andrioid** [comment]
It's pretty clear. The only generated code is `generated.go` in `graphql/graphql`. If you do schema changes or delete `resolver.go or gqlgen.yml` it will create those again, but they are programmer-owned.

Also, if you start playing with this, then I discovered that gqlgen is stripping "description/comment" from the schema so that the built-in documentation won't be available in playground/graphiql. It can be followed here: https://github.com/99designs/gqlgen/issues/118

**Comment by asim** [comment]
Should resolver.go/gqlgen.yml not be in the main repo and only graphql generated code in the other dir? I feel like just like proto dirs that we have, you only have the proto file there to generate code. Unless the generated code needs to directly reference gqlgen.yml or resolver.go. Or if gqlgen.yml is the basis for the generated code.

**Pull request merged**
